version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/Intaker.TaskManager.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=intaker_taskmanager;Username=postgres;Password=postgres
      - ConnectionStrings__ServiceBus=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://azurite:10001/devstoreaccount1;
      - ServiceBus__Topics__TaskCompleted__Name=task-completed
      - ServiceBus__Topics__TaskCompleted__SubscriptionName=task-completed-subscription
      - ServiceBus__Topics__TaskCompleted__MaxConcurrentCalls=1
      - ServiceBus__Topics__TaskCompleted__AutoCompleteMessages=true
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - azurite
    restart: on-failure
    networks:
      - intaker-taskmanager-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=intaker_taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - intaker-taskmanager-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"  # Blob
      - "10001:10001"  # Queue
      - "10002:10002"  # Table
    volumes:
      - azurite-data:/data
    networks:
      - intaker-taskmanager-network

networks:
  intaker-taskmanager-network:
    driver: bridge

volumes:
  postgres-data:
  azurite-data: 